version: "3.8"

services:
  app:
    build:
      context: ./
    ports:
      - 3000:3000
    working_dir: /app
    volumes: 
      - ./:/app
      - bundle_path:/vendor/bundle
      - node_modules:/node_modules
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dockerized_rails_app_development
    depends_on: 
      - postgres
  
  postgres:
    image: postgres:13
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dockerized_rails_app_development

volumes: 
  pgdata:
  bundle_path:
  node_modules: